language: node_js
node_js:
    - "5.5.0"
    - "node"
branches:
    except:
        - gh-pages
        - alpha
    only:
        - master
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
